#! /bin/bash
#######################
#Matt Henderson, 2015
#twitter: @hendersonn
#######################
while true
do
clear
tput bold
tput setaf 7
echo -n "           "
tput smul
echo -n "Clean Boot"
tput rmul
echo ""
echo -n "Current Kernel: " && tput setaf 1 && uname -r
echo ""
tput setaf 7
echo "Kernels List:"
tput setaf 4
dpkg --list | grep linux-image | awk '{print $2, "...............", $3}'
tput setaf 7
echo ""
echo -e -n "Run \""
tput setaf 2
echo -e -n " sudo apt-get purge linux-image-X.XX.X-XX "
tput setaf 7
echo -e "\" to remove old kernels."
echo "(Perhaps in a seperate terminal, keeping this up for reference)"
echo "Screen will refresh every five seconds, [Ctrl + C] to exit."
echo ""
echo -n "Take care as to not remove current kernel of " && tput setaf 1 && uname -r
tput sgr0
echo ""
echo ""
sleep 5
done

#Open second terminal for "apt-get" command, keeping this up for reference.
